# This GitHub Action will build the sphinx documentation and publish it to AWS S3

name: Build Sphinx Documentation and Push to Staging

on:
  workflow_dispatch:

jobs:
  publish:
    
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install sphinx-gallery && pip install sphinx_rtd_theme && pip install matplotlib && pip install numpy"
        build-command: "make html"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to staging website
      run: aws s3 sync --delete --acl public-read ./docs/build/html/ s3://dnplab-docu-staging